name: deploy-to-vercel
on: push
jobs:
  # 同步到私人仓库 main 分支，然后就会自动触发 vercel 部署
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: 'git@github.com:alibaba-web3/data-service-website.git'
          source_branch: 'main'
          destination_repo: 'git@github.com:cxw-crypto/data-service-website.git'
          destination_branch: 'main'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
